name: Post PR to Airtable
on:
  pull_request:
    types: [opened]

jobs:
  airtable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Post PR to Airtable
      env:
        AIRTABLE_API_KEY: 'keyJS9rxH1oNYtmGN'
        AIRTABLE_BASE_ID: 'appo8njU31iE50K5b'
      run: |
        const Airtable = require('airtable');
        const github = require('@actions/github');

        const apiKey = process.env.AIRTABLE_API_KEY;
        const apiBase = process.env.AIRTABLE_BASE_ID;
        const base = new Airtable({apiKey: apiKey}).base(apiBase);

        async function run() {
          const prNumber = github.context.payload.pull_request.number;
          const prTitle = github.context.payload.pull_request.title;
          const prUrl = github.context.payload.pull_request.html_url;

          await base('Pull Requests').create({
            'Number': prNumber,
            'Title': prTitle,
            'URL': prUrl
          });

          console.log('Successfully posted PR to Airtable');
        }

        run().catch(err => {
          console.error('Failed to post PR to Airtable', err);
          process.exit(1);
        });
