name: Post PR to Airtable
on:
  pull_request:
    types: [opened]

jobs:
  airtable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install

      - name: Post PR to Airtable
        env:
          AIRTABLE_API_KEY: keyJS9rxH1oNYtmGN
          AIRTABLE_BASE_ID: appo8njU31iE50K5b
        run: node airtable.js
